/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NeatSim.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CPopulationFitness : TBase
  {
    private List<CFitnessInfo> _fitnessInfos;
    private int _evaluationCount;

    public List<CFitnessInfo> FitnessInfos
    {
      get
      {
        return _fitnessInfos;
      }
      set
      {
        __isset.fitnessInfos = true;
        this._fitnessInfos = value;
      }
    }

    public int EvaluationCount
    {
      get
      {
        return _evaluationCount;
      }
      set
      {
        __isset.evaluationCount = true;
        this._evaluationCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool fitnessInfos;
      public bool evaluationCount;
    }

    public CPopulationFitness() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.List) {
              {
                FitnessInfos = new List<CFitnessInfo>();
                TList _list24 = iprot.ReadListBegin();
                for( int _i25 = 0; _i25 < _list24.Count; ++_i25)
                {
                  CFitnessInfo _elem26 = new CFitnessInfo();
                  _elem26 = new CFitnessInfo();
                  _elem26.Read(iprot);
                  FitnessInfos.Add(_elem26);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              EvaluationCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CPopulationFitness");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (FitnessInfos != null && __isset.fitnessInfos) {
        field.Name = "fitnessInfos";
        field.Type = TType.List;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, FitnessInfos.Count));
          foreach (CFitnessInfo _iter27 in FitnessInfos)
          {
            _iter27.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.evaluationCount) {
        field.Name = "evaluationCount";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(EvaluationCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CPopulationFitness(");
      sb.Append("FitnessInfos: ");
      sb.Append(FitnessInfos);
      sb.Append(",EvaluationCount: ");
      sb.Append(EvaluationCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
