/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NeatSim.Thrift
{
  public partial class CFitnessEvaluatorService {
    public interface Iface {
      CPopulationFitness calculateXorPopulationFitness(CPopulationInfo populationInfo);
      #if SILVERLIGHT
      IAsyncResult Begin_calculateXorPopulationFitness(AsyncCallback callback, object state, CPopulationInfo populationInfo);
      CPopulationFitness End_calculateXorPopulationFitness(IAsyncResult asyncResult);
      #endif
      CFitnessInfo calculateXorPhenotypeFitness(CFastCyclicNetwork ann);
      #if SILVERLIGHT
      IAsyncResult Begin_calculateXorPhenotypeFitness(AsyncCallback callback, object state, CFastCyclicNetwork ann);
      CFitnessInfo End_calculateXorPhenotypeFitness(IAsyncResult asyncResult);
      #endif
    }

    public class Client : Iface {
      public Client(TProtocol prot) : this(prot, prot)
      {
      }

      public Client(TProtocol iprot, TProtocol oprot)
      {
        iprot_ = iprot;
        oprot_ = oprot;
      }

      protected TProtocol iprot_;
      protected TProtocol oprot_;
      protected int seqid_;

      public TProtocol InputProtocol
      {
        get { return iprot_; }
      }
      public TProtocol OutputProtocol
      {
        get { return oprot_; }
      }


      
      #if SILVERLIGHT
      public IAsyncResult Begin_calculateXorPopulationFitness(AsyncCallback callback, object state, CPopulationInfo populationInfo)
      {
        return send_calculateXorPopulationFitness(callback, state, populationInfo);
      }

      public CPopulationFitness End_calculateXorPopulationFitness(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_calculateXorPopulationFitness();
      }

      #endif

      public CPopulationFitness calculateXorPopulationFitness(CPopulationInfo populationInfo)
      {
        #if !SILVERLIGHT
        send_calculateXorPopulationFitness(populationInfo);
        return recv_calculateXorPopulationFitness();

        #else
        var asyncResult = Begin_calculateXorPopulationFitness(null, null, populationInfo);
        return End_calculateXorPopulationFitness(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_calculateXorPopulationFitness(AsyncCallback callback, object state, CPopulationInfo populationInfo)
      #else
      public void send_calculateXorPopulationFitness(CPopulationInfo populationInfo)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("calculateXorPopulationFitness", TMessageType.Call, seqid_));
        calculateXorPopulationFitness_args args = new calculateXorPopulationFitness_args();
        args.PopulationInfo = populationInfo;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public CPopulationFitness recv_calculateXorPopulationFitness()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        calculateXorPopulationFitness_result result = new calculateXorPopulationFitness_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "calculateXorPopulationFitness failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_calculateXorPhenotypeFitness(AsyncCallback callback, object state, CFastCyclicNetwork ann)
      {
        return send_calculateXorPhenotypeFitness(callback, state, ann);
      }

      public CFitnessInfo End_calculateXorPhenotypeFitness(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_calculateXorPhenotypeFitness();
      }

      #endif

      public CFitnessInfo calculateXorPhenotypeFitness(CFastCyclicNetwork ann)
      {
        #if !SILVERLIGHT
        send_calculateXorPhenotypeFitness(ann);
        return recv_calculateXorPhenotypeFitness();

        #else
        var asyncResult = Begin_calculateXorPhenotypeFitness(null, null, ann);
        return End_calculateXorPhenotypeFitness(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_calculateXorPhenotypeFitness(AsyncCallback callback, object state, CFastCyclicNetwork ann)
      #else
      public void send_calculateXorPhenotypeFitness(CFastCyclicNetwork ann)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("calculateXorPhenotypeFitness", TMessageType.Call, seqid_));
        calculateXorPhenotypeFitness_args args = new calculateXorPhenotypeFitness_args();
        args.Ann = ann;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public CFitnessInfo recv_calculateXorPhenotypeFitness()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        calculateXorPhenotypeFitness_result result = new calculateXorPhenotypeFitness_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "calculateXorPhenotypeFitness failed: unknown result");
      }

    }
    public class Processor : TProcessor {
      public Processor(Iface iface)
      {
        iface_ = iface;
        processMap_["calculateXorPopulationFitness"] = calculateXorPopulationFitness_Process;
        processMap_["calculateXorPhenotypeFitness"] = calculateXorPhenotypeFitness_Process;
      }

      protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
      private Iface iface_;
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public bool Process(TProtocol iprot, TProtocol oprot)
      {
        try
        {
          TMessage msg = iprot.ReadMessageBegin();
          ProcessFunction fn;
          processMap_.TryGetValue(msg.Name, out fn);
          if (fn == null) {
            TProtocolUtil.Skip(iprot, TType.Struct);
            iprot.ReadMessageEnd();
            TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
            x.Write(oprot);
            oprot.WriteMessageEnd();
            oprot.Transport.Flush();
            return true;
          }
          fn(msg.SeqID, iprot, oprot);
        }
        catch (IOException)
        {
          return false;
        }
        return true;
      }

      public void calculateXorPopulationFitness_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        calculateXorPopulationFitness_args args = new calculateXorPopulationFitness_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        calculateXorPopulationFitness_result result = new calculateXorPopulationFitness_result();
        result.Success = iface_.calculateXorPopulationFitness(args.PopulationInfo);
        oprot.WriteMessageBegin(new TMessage("calculateXorPopulationFitness", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void calculateXorPhenotypeFitness_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        calculateXorPhenotypeFitness_args args = new calculateXorPhenotypeFitness_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        calculateXorPhenotypeFitness_result result = new calculateXorPhenotypeFitness_result();
        result.Success = iface_.calculateXorPhenotypeFitness(args.Ann);
        oprot.WriteMessageBegin(new TMessage("calculateXorPhenotypeFitness", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class calculateXorPopulationFitness_args : TBase
    {
      private CPopulationInfo _populationInfo;

      public CPopulationInfo PopulationInfo
      {
        get
        {
          return _populationInfo;
        }
        set
        {
          __isset.populationInfo = true;
          this._populationInfo = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool populationInfo;
      }

      public calculateXorPopulationFitness_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                PopulationInfo = new CPopulationInfo();
                PopulationInfo.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("calculateXorPopulationFitness_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (PopulationInfo != null && __isset.populationInfo) {
          field.Name = "populationInfo";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          PopulationInfo.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("calculateXorPopulationFitness_args(");
        sb.Append("PopulationInfo: ");
        sb.Append(PopulationInfo== null ? "<null>" : PopulationInfo.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class calculateXorPopulationFitness_result : TBase
    {
      private CPopulationFitness _success;

      public CPopulationFitness Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public calculateXorPopulationFitness_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new CPopulationFitness();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("calculateXorPopulationFitness_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("calculateXorPopulationFitness_result(");
        sb.Append("Success: ");
        sb.Append(Success== null ? "<null>" : Success.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class calculateXorPhenotypeFitness_args : TBase
    {
      private CFastCyclicNetwork _ann;

      public CFastCyclicNetwork Ann
      {
        get
        {
          return _ann;
        }
        set
        {
          __isset.ann = true;
          this._ann = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool ann;
      }

      public calculateXorPhenotypeFitness_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Ann = new CFastCyclicNetwork();
                Ann.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("calculateXorPhenotypeFitness_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Ann != null && __isset.ann) {
          field.Name = "ann";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ann.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("calculateXorPhenotypeFitness_args(");
        sb.Append("Ann: ");
        sb.Append(Ann== null ? "<null>" : Ann.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class calculateXorPhenotypeFitness_result : TBase
    {
      private CFitnessInfo _success;

      public CFitnessInfo Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public calculateXorPhenotypeFitness_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new CFitnessInfo();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("calculateXorPhenotypeFitness_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("calculateXorPhenotypeFitness_result(");
        sb.Append("Success: ");
        sb.Append(Success== null ? "<null>" : Success.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }

  }
}
